services:
db:
image: postgres:16
container_name: portfolio_pg
environment:
POSTGRES_DB: portfolio
POSTGRES_USER: portfolio
POSTGRES_PASSWORD: portfolio
ports:
  - "5432:5432"
volumes:
  - pgdata:/var/lib/postgresql/data
volumes:
pgdata: